name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable corepack for yarn berry
        run: corepack enable

      - name: Install NPM packages
        run: yarn install --frozen-lockfile

      - name: Build the packages
        run: yarn lerna run build
