name: Lint

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install NPM packages
        run: yarn install --frozen-lockfile

      - name: Run linter
        run: yarn lint

      - name: Run prettier check
        run: yarn prettier --check .
